Test File for Button Component
thekavikumar/love-simple-ui pull request #213
Opened 2023-07-02 17:49 UTC by Killer2OP

## Title
Test file

## Proposed Changes

## Check List (Check all the applicable boxes)

- [ ] Bug(s) fixed
- [ ] Enhancement done
- [X] New Feature(s) added
- [ ] Documentation changed
- [ ] All new and existing tests passed.
- [ ] My code follows the code style of this project.

## Screenshots (if any)

![image](https://github.com/thekavikumar/love-simple-ui/assets/111378171/aee6afb6-b661-4e79-87a6-cd4596b309a3)

2023-07-02 17:50 UTC, Killer2OP commented
wait for me to include all the files then merge it.

2023-07-02 17:52 UTC, Killer2OP commented
@thekavikumar Now you can review the file.

2023-07-06 17:53 UTC, Killer2OP commented
@thekavikumar Can you please review the PR

2023-07-16 16:16 UTC, thekavikumar commented on package.json
> +  "version": "1.0.24",
pls update the crt version

2023-07-16 16:16 UTC, thekavikumar commented on package.json
> -  "module": "dist/index.mjs",
why did you remove it?

2023-07-16 16:17 UTC, thekavikumar commented on package.json
> -    "clsx": "^1.2.1",
add the deps

2023-07-16 16:18 UTC, thekavikumar commented on package.json
> +    "tailwind-merge": "^1.13.2"
add these as dev deps

2023-07-16 16:18 UTC, thekavikumar requested changes
resolve the comments!

2023-07-16 16:22 UTC, Killer2OP commented
> resolve the comments!

OK

2023-07-16 18:29 UTC, Killer2OP commented
@thekavikumar DONE.

2024-03-13 18:31 UTC, closed without merging